trigger:
  branches:
    include:
      - main

variables:
  - group: aws-credentials
  - name: awsRegion
    value: 'us-east-1'
  - name: ecrRepository
    value: 'my-aws-app'
  - name: imageTag
    value: 'latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image to ECR
    jobs:
      - job: DockerBuildPush
        displayName: Docker Build & Push
        steps:
          - checkout: self

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Setting AWS Region..."
                export AWS_DEFAULT_REGION=$(awsRegion)

                echo "Getting AWS Account ID..."
                account_id=$(aws sts get-caller-identity --query Account --output text)
                ecr_url="$account_id.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

                echo "Logging into ECR..."
                aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ecr_url

                echo "Building Docker image..."
               # docker build -t $(ecrRepository):$(imageTag) .
                docker build -t $(ecrRepository):$(imageTag) -f app/Dockerfile app

                echo "Tagging Docker image..."
                docker tag $(ecrRepository):$(imageTag) $ecr_url/$(ecrRepository):$(imageTag)

                echo "Pushing Docker image to ECR..."
                docker push $ecr_url/$(ecrRepository):$(imageTag)

                echo "✅ Docker image pushed to ECR successfully!"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
