trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: aws-credentials
    AWS_REGION: 'us-east-1'

stages:
  - stage: Terraform
    jobs:
    - job: DeployInfra
      steps:
      - checkout: self
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - script: |
          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

  - stage: DeployApp
    dependsOn: Terraform
    jobs:
    - job: BuildPushImage
      steps:
      - script: |
          cd app
          docker build -t my-aws-app .
          aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin <your_aws_account_id>.dkr.ecr.$(AWS_REGION).amazonaws.com
          docker tag my-aws-app <your_aws_account_id>.dkr.ecr.$(AWS_REGION).amazonaws.com/my-aws-app
          docker push <your_aws_account_id>.dkr.ecr.$(AWS_REGION).amazonaws.com/my-aws-app
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
